### ISSUE TITLE
Code formatting doesn't match .editorconfig

### ISSUE THREAD

**Issue by KirillOsenkov** [praeclarum/ListDiff#3]
What would you prefer to change? Fix the code to match the editorconfig or fix the editorconfig to match the code? Editorconfig currently insists on placing the opening curly on the previous line.

**Comment by praeclarum** [comment]
I just reviewed the editorconfig and it seems right. The curly should be on the same line as the statement except for types and methods.

Which code needs fixing? ListDiff.cs seemed OK.

**Comment by KirillOsenkov** [comment]
Try formatting the file ListDiff.cs in latest VS 2017 - I think it should be `types, methods`, not `types:methods` (comma separated: https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference#c-formatting-settings)

**Comment by KirillOsenkov** [comment]
https://github.com/praeclarum/ListDiff/pull/6 seems to be fixing it.

**Comment by praeclarum** [comment]
I've merged #6 

Thank you!
